import fs from 'fs';
import path from 'path';
import {
  discoverSessionDirs,
  formatAgentScenarioLabel,
  readSessionStats,
  type SessionDescriptor,
  type SessionStatsMetrics,
} from './session-stats.js';

function loadEnv(envPath: string): Record<string, string> {
  const env: Record<string, string> = {};
  try {
    const content = fs.readFileSync(envPath, 'utf8');
    for (const line of content.split('\n')) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('#')) continue;
      const eqIdx = trimmed.indexOf('=');
      if (eqIdx === -1) continue;
      const key = trimmed.slice(0, eqIdx).trim();
      const val = trimmed.slice(eqIdx + 1).trim();
      env[key] = val;
    }
  } catch {
    // .env not found — rely on process.env
  }
  return env;
}

interface ScenarioMetrics extends SessionStatsMetrics {
  agent: string;
  scenario: string;
  dirCount: number;
}

function keyFor(agent: string, scenario: string): string {
  return `${agent}:${scenario}`;
}

async function cleanCliDirs(sessions: SessionDescriptor[]): Promise<void> {
  for (const session of sessions) {
    try {
      const cliPath = path.join(session.dir, "cli");
      //first, copy .edgee/session-stats/*.json to the root of the session directory
      const statsPath = path.join(cliPath, ".edgee/session-stats");
      const statsFiles = await fs.promises.readdir(statsPath);
      for (const file of statsFiles) {
        await fs.promises.copyFile(
          path.join(statsPath, file),
          path.join(session.dir, file),
        );
        // rename this file to session-stats.json
        await fs.promises.rename(
          path.join(session.dir, file),
          path.join(session.dir, "session-stats.json"),
        );
        // stop the loop
        break;
      }
      await fs.promises.rm(cliPath, { recursive: true, force: true });
    } catch (error) {
      console.error(`Error cleaning ${session.dir}: ${error}`);
    }
    console.log(`Cleaned: ${session.dir}`);
  }
}

function createEmptyMetrics(agent: string, scenario: string): ScenarioMetrics {
  return {
    agent,
    scenario,
    dirCount: 0,
    totalInputTokens: 0,
    totalOutputTokens: 0,
    totalCost: 0,
    cacheReadTokens: 0,
    cacheCreationTokens: 0,
    apiDurationMs: 0,
    byModel: {},
  };
}

function aggregateSessions(sessions: SessionDescriptor[]): Record<string, ScenarioMetrics> {
  const aggregated: Record<string, ScenarioMetrics> = {};

  for (const session of sessions) {
    const metrics = readSessionStats(session.dir);
    if (!metrics) continue;

    const key = keyFor(session.agent, session.scenario);
    if (!aggregated[key]) {
      aggregated[key] = createEmptyMetrics(session.agent, session.scenario);
    }

    const target = aggregated[key];
    target.dirCount += 1;
    target.totalInputTokens += metrics.totalInputTokens;
    target.totalOutputTokens += metrics.totalOutputTokens;
    target.totalCost += metrics.totalCost;
    target.cacheReadTokens += metrics.cacheReadTokens;
    target.cacheCreationTokens += metrics.cacheCreationTokens;
    target.apiDurationMs += metrics.apiDurationMs;

    for (const [model, usage] of Object.entries(metrics.byModel)) {
      if (!target.byModel[model]) {
        target.byModel[model] = {
          inputTokens: 0,
          outputTokens: 0,
          cacheReadInputTokens: 0,
          cacheCreationInputTokens: 0,
          costUSD: 0,
        };
      }

      const bucket = target.byModel[model];
      bucket.inputTokens += usage.inputTokens;
      bucket.outputTokens += usage.outputTokens;
      bucket.cacheReadInputTokens += usage.cacheReadInputTokens;
      bucket.cacheCreationInputTokens += usage.cacheCreationInputTokens;
      bucket.costUSD += usage.costUSD;
    }
  }

  return aggregated;
}

function sortMetrics(scenarios: Record<string, ScenarioMetrics>): ScenarioMetrics[] {
  return Object.values(scenarios).sort((a, b) => {
    const agentCmp = a.agent.localeCompare(b.agent);
    if (agentCmp !== 0) return agentCmp;
    return a.scenario.localeCompare(b.scenario);
  });
}

function buildPrompt(scenarios: Record<string, ScenarioMetrics>): string {
  const displayScenarios = Object.fromEntries(
    Object.entries(scenarios).map(([key, metrics]) => [
      key,
      {
        ...metrics,
        label: formatAgentScenarioLabel(metrics.agent, metrics.scenario),
      },
    ]),
  );

  return `You are analyzing token usage data from coding-agent benchmark sessions.

Each scenario key is in the form "agent:scenario", where:
- agent is the coding agent used for the run
- scenario is the benchmark setup (normal, edgee, rtk)

Here is the aggregated token usage data:

\`\`\`json
${JSON.stringify(displayScenarios, null, 2)}
\`\`\`

Metric definitions:
- totalInputTokens: fresh input tokens sent to the API
- totalOutputTokens: tokens generated by the model
- cacheReadTokens: cached input tokens served cheaply
- cacheCreationTokens: tokens written into cache
- totalCost: USD cost
- byModel: per-model token and cost breakdown

Please provide a concise analytical Markdown report that:
1. Compares all reported agent/scenario combinations by total input+output tokens and cost
2. Highlights savings of each optimized scenario versus the same agent's normal baseline when that baseline exists
3. Compares cache efficiency across all combinations
4. Ranks combinations by cost and calls out the cheapest
5. Gives a production recommendation, making clear whether the recommendation differs by agent

Use the provided label field for display names when referring to scenarios. Include a summary table.`;
}

function buildMarkdownReport(
  generatedAt: string,
  scenarios: Record<string, ScenarioMetrics>,
  analysis: string,
): string {
  const fmt = (n: number) => n.toLocaleString('en-US');
  const rows = sortMetrics(scenarios).map((metrics) => {
    const total = metrics.totalInputTokens + metrics.totalOutputTokens;
    const totalCache = metrics.cacheReadTokens + metrics.cacheCreationTokens + metrics.totalInputTokens;
    const hitRate = totalCache === 0 ? 0 : (metrics.cacheReadTokens / totalCache) * 100;

    return {
      label: formatAgentScenarioLabel(metrics.agent, metrics.scenario),
      metrics,
      total,
      hitRate,
    };
  });

  const lines: string[] = [
    `# Token Usage Analysis Report`,
    ``,
    `_Generated at: ${generatedAt}_`,
    ``,
    `## Raw Metrics`,
    ``,
    `| Scenario | Runs | Input Tokens | Output Tokens | Total I/O | Cache Reads | Cache Creates | Cache Hit Rate | Cost (USD) |`,
    `|---|---:|---:|---:|---:|---:|---:|---:|---:|`,
    ...rows.map(({ label, metrics, total, hitRate }) =>
      `| **${label}** | ${metrics.dirCount} | ${fmt(metrics.totalInputTokens)} | ${fmt(metrics.totalOutputTokens)} | ${fmt(total)} | ${fmt(metrics.cacheReadTokens)} | ${fmt(metrics.cacheCreationTokens)} | ${hitRate.toFixed(1)}% | $${metrics.totalCost.toFixed(4)} |`,
    ),
    ``,
    `## Model Breakdown`,
    ``,
  ];

  for (const { label, metrics } of rows) {
    lines.push(`### ${label}`);
    lines.push(``);
    lines.push(`| Model | Input | Output | Cache Reads | Cache Creates | Cost (USD) |`);
    lines.push(`|---|---:|---:|---:|---:|---:|`);

    const models = Object.entries(metrics.byModel).sort(([a], [b]) => a.localeCompare(b));
    if (models.length === 0) {
      lines.push(`| _No model data_ | 0 | 0 | 0 | 0 | $0.0000 |`);
    } else {
      for (const [model, usage] of models) {
        lines.push(
          `| ${model} | ${fmt(usage.inputTokens)} | ${fmt(usage.outputTokens)} | ${fmt(usage.cacheReadInputTokens)} | ${fmt(usage.cacheCreationInputTokens)} | $${usage.costUSD.toFixed(4)} |`,
        );
      }
    }
    lines.push(``);
  }

  lines.push(`## Analysis`);
  lines.push(``);
  lines.push(analysis);

  return lines.join('\n');
}

async function main() {
  const cwd = process.cwd();
  const env = { ...loadEnv(path.join(cwd, '.env')), ...process.env };

  const apiToken = env.EDGEE_API_TOKEN_REPORT;
  if (!apiToken) {
    throw new Error('EDGEE_API_TOKEN_REPORT not found in .env or environment');
  }

  console.log('Finding benchmark directories...');
  const sessions = discoverSessionDirs(cwd, false);
  for (const session of sessions) {
    console.log(`  ${session.agent}:${session.scenario} -> ${path.basename(session.dir)}`);
  }

  if (sessions.length === 0) {
    console.error('No benchmark directories found');
    process.exit(1);
  }

  console.log('\nCleaning cli/ directories...');
  await cleanCliDirs(sessions);

  console.log('\nParsing session-stats.json files...');
  const scenarios = aggregateSessions(sessions);
  const rows = sortMetrics(scenarios);

  if (rows.length === 0) {
    console.error('No readable session-stats.json files found');
    process.exit(1);
  }

  for (const metrics of rows) {
    const total = metrics.totalInputTokens + metrics.totalOutputTokens;
    console.log(
      `  ${metrics.agent}:${metrics.scenario}: ${metrics.dirCount} run(s), ${total.toLocaleString()} total tokens, $${metrics.totalCost.toFixed(4)}`,
    );
  }

  console.log('\nCalling Claude via Edgee API...');
  const prompt = buildPrompt(scenarios);

  const edgeeBaseUrl = env.EDGEE_BASE_URL ?? 'https://api.edgee.ai';
  const res = await fetch(`${edgeeBaseUrl}/v1/chat/completions`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${apiToken}`,
    },
    body: JSON.stringify({
      model: 'anthropic/claude-sonnet-4-6',
      messages: [{ role: 'user', content: prompt }],
    }),
  });

  if (!res.ok) {
    const errBody = await res.text();
    throw new Error(`Edgee API error ${res.status}: ${errBody}`);
  }

  const data = await res.json() as {
    choices: Array<{ message: { content: string } }>;
    usage?: unknown;
    compression?: unknown;
  };

  const analysisText: string = data.choices[0]?.message?.content ?? '';
  const compressionInfo = data.compression ?? null;

  if (compressionInfo) {
    console.log(`  Edgee compression: ${JSON.stringify(compressionInfo)}`);
  }

  console.log("\n" + "─".repeat(80));
  console.log("ANALYSIS REPORT");
  console.log("─".repeat(80));
  console.log(analysisText);
  console.log('─'.repeat(80));

  const generatedAt = new Date().toISOString();
  const reportData = {
    generatedAt,
    scenarios,
    analysis: analysisText,
  };

  const reportBase = `report-${generatedAt.replace(/[:.]/g, '-')}`;
  const reportFile = path.join(cwd, `${reportBase}.json`);
  fs.writeFileSync(reportFile, JSON.stringify(reportData, null, 2));
  console.log(`\nReport saved to: ${reportFile}`);

  const mdContent = buildMarkdownReport(generatedAt, scenarios, analysisText);
  const mdFile = path.join(cwd, `${reportBase}.md`);
  fs.writeFileSync(mdFile, mdContent);
  console.log(`Report saved to: ${mdFile}`);
}

main().catch((err) => {
  console.error('Error:', err);
  process.exit(1);
});
